// Generated by IcedCoffeeScript 1.3.3g
(function() {
  var Generator, crypto, iced, o, __iced_deferrals, __iced_k, __iced_k_noop,
    _this = this;

  iced = require('iced-coffee-script').iced;
  __iced_k = __iced_k_noop = function() {};

  crypto = require('crypto');

  exports.Generator = Generator = (function() {

    function Generator() {}

    Generator.prototype.byte = function(cb) {
      var buf, ex, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "src/main.iced",
          funcname: "Generator.byte"
        });
        crypto.randomBytes(1, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              ex = arguments[0];
              return buf = arguments[1];
            };
          })(),
          lineno: 8
        }));
        __iced_deferrals._fulfill();
      })(function() {
        return cb(buf[0]);
      });
    };

    Generator.prototype.integer = function(cb, signed) {
      var buf, ex, i, r, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "src/main.iced",
          funcname: "Generator.integer"
        });
        crypto.randomBytes(4, __iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              ex = arguments[0];
              return buf = arguments[1];
            };
          })(),
          lineno: 12
        }));
        __iced_deferrals._fulfill();
      })(function() {
        var _i;
        r = 0;
        for (i = _i = 0; _i < 4; i = ++_i) {
          r *= 256;
          r += buf[i];
        }
        if (buf[3] >= 128 && signed) r = 0 - r;
        return cb(r);
      });
    };

    Generator.prototype.float = function(cb) {
      var d, n, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "src/main.iced",
          funcname: "Generator.float"
        });
        _this.integer(__iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return n = arguments[0];
            };
          })(),
          lineno: 20
        }), true);
        __iced_deferrals._fulfill();
      })(function() {
        (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "src/main.iced",
            funcname: "Generator.float"
          });
          _this.integer(__iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                return d = arguments[0];
              };
            })(),
            lineno: 22
          }));
          __iced_deferrals._fulfill();
        })(function() {
          if (d === 0) d = 1;
          return cb(n / d);
        });
      });
    };

    Generator.prototype.string = function(n, cb) {
      var buf, ex, n, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      (function(__iced_k) {
        if (!n) {
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "src/main.iced",
              funcname: "Generator.string"
            });
            _this.integer(__iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  return n = arguments[0];
                };
              })(),
              lineno: 28
            }));
            __iced_deferrals._fulfill();
          })(function() {
            return __iced_k(n = n % 200);
          });
        } else {
          return __iced_k();
        }
      })(function() {
        (function(__iced_k) {
          __iced_deferrals = new iced.Deferrals(__iced_k, {
            parent: ___iced_passed_deferral,
            filename: "src/main.iced",
            funcname: "Generator.string"
          });
          crypto.randomBytes(n, __iced_deferrals.defer({
            assign_fn: (function() {
              return function() {
                ex = arguments[0];
                return buf = arguments[1];
              };
            })(),
            lineno: 30
          }));
          __iced_deferrals._fulfill();
        })(function() {
          return cb(buf.toString('base64'));
        });
      });
    };

    Generator.prototype.array = function(n, cb, d) {
      var i, n, r, x, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      (function(__iced_k) {
        if (!n) {
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "src/main.iced",
              funcname: "Generator.array"
            });
            _this.integer(__iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  return n = arguments[0];
                };
              })(),
              lineno: 35
            }));
            __iced_deferrals._fulfill();
          })(function() {
            return __iced_k(n = n % 10);
          });
        } else {
          return __iced_k();
        }
      })(function() {
        r = [];
        (function(__iced_k) {
          var _i, _results, _while;
          i = 0;
          _results = [];
          _while = function(__iced_k) {
            var _break, _continue, _next;
            _break = function() {
              return __iced_k(_results);
            };
            _continue = function() {
              return iced.trampoline(function() {
                ++i;
                return _while(__iced_k);
              });
            };
            _next = function(__iced_next_arg) {
              _results.push(__iced_next_arg);
              return _continue();
            };
            if (!(i < n)) {
              return _break();
            } else {
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "src/main.iced",
                  funcname: "Generator.array"
                });
                _this.json(__iced_deferrals.defer({
                  assign_fn: (function() {
                    return function() {
                      return x = arguments[0];
                    };
                  })(),
                  lineno: 38
                }), d + 1);
                __iced_deferrals._fulfill();
              })(function() {
                return _next(r[i] = x);
              });
            }
          };
          _while(__iced_k);
        })(function() {
          return cb(r);
        });
      });
    };

    Generator.prototype.obj = function(n, cb, d) {
      var i, k, n, r, v, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      if (d == null) d = 0;
      (function(__iced_k) {
        if (!n) {
          (function(__iced_k) {
            __iced_deferrals = new iced.Deferrals(__iced_k, {
              parent: ___iced_passed_deferral,
              filename: "src/main.iced",
              funcname: "Generator.obj"
            });
            _this.integer(__iced_deferrals.defer({
              assign_fn: (function() {
                return function() {
                  return n = arguments[0];
                };
              })(),
              lineno: 45
            }));
            __iced_deferrals._fulfill();
          })(function() {
            return __iced_k(n %= 8);
          });
        } else {
          return __iced_k();
        }
      })(function() {
        r = {};
        (function(__iced_k) {
          var _i, _results, _while;
          i = 0;
          _results = [];
          _while = function(__iced_k) {
            var _break, _continue, _next;
            _break = function() {
              return __iced_k(_results);
            };
            _continue = function() {
              return iced.trampoline(function() {
                ++i;
                return _while(__iced_k);
              });
            };
            _next = function(__iced_next_arg) {
              _results.push(__iced_next_arg);
              return _continue();
            };
            if (!(i <= n)) {
              return _break();
            } else {
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "src/main.iced",
                  funcname: "Generator.obj"
                });
                _this.string(10, __iced_deferrals.defer({
                  assign_fn: (function() {
                    return function() {
                      return k = arguments[0];
                    };
                  })(),
                  lineno: 49
                }));
                __iced_deferrals._fulfill();
              })(function() {
                (function(__iced_k) {
                  __iced_deferrals = new iced.Deferrals(__iced_k, {
                    parent: ___iced_passed_deferral,
                    filename: "src/main.iced",
                    funcname: "Generator.obj"
                  });
                  _this.json(__iced_deferrals.defer({
                    assign_fn: (function() {
                      return function() {
                        return v = arguments[0];
                      };
                    })(),
                    lineno: 49
                  }), d + 1);
                  __iced_deferrals._fulfill();
                })(function() {
                  return _next(r[k] = v);
                });
              });
            }
          };
          _while(__iced_k);
        })(function() {
          return cb(r);
        });
      });
    };

    Generator.prototype.json = function(cb, d) {
      var b, r, ret, ___iced_passed_deferral, __iced_deferrals, __iced_k,
        _this = this;
      __iced_k = __iced_k_noop;
      ___iced_passed_deferral = iced.findDeferral(arguments);
      if (d == null) d = 0;
      (function(__iced_k) {
        __iced_deferrals = new iced.Deferrals(__iced_k, {
          parent: ___iced_passed_deferral,
          filename: "src/main.iced",
          funcname: "Generator.json"
        });
        _this.byte(__iced_deferrals.defer({
          assign_fn: (function() {
            return function() {
              return b = arguments[0];
            };
          })(),
          lineno: 55
        }));
        __iced_deferrals._fulfill();
      })(function() {
        b %= 8;
        ret = null;
        if (d > 4 && b > 5) b %= 5;
        (function(__iced_k) {
          switch (b) {
            case 0:
              return __iced_k(r = false);
            case 1:
              return __iced_k(r = true);
            case 2:
              return __iced_k(r = null);
            case 3:
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "src/main.iced",
                  funcname: "Generator.json"
                });
                _this.integer(__iced_deferrals.defer({
                  assign_fn: (function() {
                    return function() {
                      return r = arguments[0];
                    };
                  })(),
                  lineno: 67
                }), true);
                __iced_deferrals._fulfill();
              })(__iced_k);
              break;
            case 4:
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "src/main.iced",
                  funcname: "Generator.json"
                });
                _this.float(__iced_deferrals.defer({
                  assign_fn: (function() {
                    return function() {
                      return r = arguments[0];
                    };
                  })(),
                  lineno: 70
                }));
                __iced_deferrals._fulfill();
              })(__iced_k);
              break;
            case 5:
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "src/main.iced",
                  funcname: "Generator.json"
                });
                _this.string(null, __iced_deferrals.defer({
                  assign_fn: (function() {
                    return function() {
                      return r = arguments[0];
                    };
                  })(),
                  lineno: 72
                }));
                __iced_deferrals._fulfill();
              })(__iced_k);
              break;
            case 6:
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "src/main.iced",
                  funcname: "Generator.json"
                });
                _this.array(null, __iced_deferrals.defer({
                  assign_fn: (function() {
                    return function() {
                      return r = arguments[0];
                    };
                  })(),
                  lineno: 73
                }), d);
                __iced_deferrals._fulfill();
              })(__iced_k);
              break;
            case 7:
              (function(__iced_k) {
                __iced_deferrals = new iced.Deferrals(__iced_k, {
                  parent: ___iced_passed_deferral,
                  filename: "src/main.iced",
                  funcname: "Generator.json"
                });
                _this.obj(null, __iced_deferrals.defer({
                  assign_fn: (function() {
                    return function() {
                      return r = arguments[0];
                    };
                  })(),
                  lineno: 75
                }), d);
                __iced_deferrals._fulfill();
              })(__iced_k);
          }
        })(function() {
          return cb(r);
        });
      });
    };

    return Generator;

  })();

  exports.json = function(cb) {
    var g, o, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    g = new Generator();
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "src/main.iced",
        funcname: "json"
      });
      g.json(__iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            return o = arguments[0];
          };
        })(),
        lineno: 83
      }));
      __iced_deferrals._fulfill();
    })(function() {
      return cb(o);
    });
  };

  exports.obj = function(cb, n) {
    var g, o, ___iced_passed_deferral, __iced_deferrals, __iced_k,
      _this = this;
    __iced_k = __iced_k_noop;
    ___iced_passed_deferral = iced.findDeferral(arguments);
    if (n == null) n = null;
    g = new Generator();
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        parent: ___iced_passed_deferral,
        filename: "src/main.iced",
        funcname: "obj"
      });
      g.obj(n, __iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            return o = arguments[0];
          };
        })(),
        lineno: 90
      }));
      __iced_deferrals._fulfill();
    })(function() {
      return cb(o);
    });
  };

  if (false) {
    (function(__iced_k) {
      __iced_deferrals = new iced.Deferrals(__iced_k, {
        filename: "src/main.iced"
      });
      exports.obj(__iced_deferrals.defer({
        assign_fn: (function() {
          return function() {
            return o = arguments[0];
          };
        })(),
        lineno: 97
      }));
      __iced_deferrals._fulfill();
    })(function() {
      return __iced_k(console.log(o));
    });
  } else {
    __iced_k();
  }

}).call(this);
